version: '3.5'

services:
  drone-server:
    image: drone/drone:1.2.1
    ports:
      - 8000:80
      - 9000:443
    networks:
      - drone
    volumes:
      - ./drone-data:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./drone.env
    restart: always
    environment:
      - DRONE_GITLAB_SKIP_VERIFY=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_OPEN=false

  drone-agent:
    image: drone/agent:1.2.1
    command: agent
    restart: always
    depends_on:
      - drone-server
    networks:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./drone.env

networks:
  drone:
    name: drone_network
